/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ImportRouteImport } from './routes/import'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AcademicsLessonsRouteImport } from './routes/academics.lessons'
import { Route as AcademicsSubjectsRouteImport } from './routes/academics.subjects'
import { Route as AcademicsSyllabusRouteImport } from './routes/academics.syllabus'
import { Route as AcademicsTimetableRouteImport } from './routes/academics.timetable'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as ResultsBatchIdRouteImport } from './routes/results.$batchId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as TeachersTeacherIdRouteImport } from './routes/teachers.$teacherId'
import { Route as TeacherClassClassIdRouteImport } from './routes/teacher.class.$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsLessonsRoute = AcademicsLessonsRouteImport.update({
  id: '/academics/lessons',
  path: '/academics/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSubjectsRoute = AcademicsSubjectsRouteImport.update({
  id: '/academics/subjects',
  path: '/academics/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSyllabusRoute = AcademicsSyllabusRouteImport.update({
  id: '/academics/syllabus',
  path: '/academics/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsTimetableRoute = AcademicsTimetableRouteImport.update({
  id: '/academics/timetable',
  path: '/academics/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsBatchIdRoute = ResultsBatchIdRouteImport.update({
  id: '/results/$batchId',
  path: '/results/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/teacher/classes',
  path: '/teacher/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdRoute = TeachersTeacherIdRouteImport.update({
  id: '/teachers/$teacherId',
  path: '/teachers/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassClassIdRoute = TeacherClassClassIdRouteImport.update({
  id: '/teacher/class/$classId',
  path: '/teacher/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/academics/lessons': typeof AcademicsLessonsRoute
  '/academics/subjects': typeof AcademicsSubjectsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/timetable': typeof AcademicsTimetableRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/results/$batchId': typeof ResultsBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/academics/lessons': typeof AcademicsLessonsRoute
  '/academics/subjects': typeof AcademicsSubjectsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/timetable': typeof AcademicsTimetableRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/results/$batchId': typeof ResultsBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/classes': typeof ClassesIndexRoute
  '/results': typeof ResultsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/attendance': typeof AttendanceRoute
  '/communication': typeof CommunicationRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/academics/lessons': typeof AcademicsLessonsRoute
  '/academics/subjects': typeof AcademicsSubjectsRoute
  '/academics/syllabus': typeof AcademicsSyllabusRoute
  '/academics/timetable': typeof AcademicsTimetableRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/results/$batchId': typeof ResultsBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/attendance'
    | '/communication'
    | '/import'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/academics/lessons'
    | '/academics/subjects'
    | '/academics/syllabus'
    | '/academics/timetable'
    | '/classes/$classId'
    | '/results/$batchId'
    | '/students/$studentId'
    | '/teacher/classes'
    | '/teachers/$teacherId'
    | '/classes/'
    | '/results/'
    | '/students/'
    | '/teacher/'
    | '/teachers/'
    | '/teacher/class/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admissions'
    | '/attendance'
    | '/communication'
    | '/import'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/academics/lessons'
    | '/academics/subjects'
    | '/academics/syllabus'
    | '/academics/timetable'
    | '/classes/$classId'
    | '/results/$batchId'
    | '/students/$studentId'
    | '/teacher/classes'
    | '/teachers/$teacherId'
    | '/classes'
    | '/results'
    | '/students'
    | '/teacher'
    | '/teachers'
    | '/teacher/class/$classId'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/attendance'
    | '/communication'
    | '/import'
    | '/onboarding'
    | '/reports'
    | '/settings'
    | '/academics/lessons'
    | '/academics/subjects'
    | '/academics/syllabus'
    | '/academics/timetable'
    | '/classes/$classId'
    | '/results/$batchId'
    | '/students/$studentId'
    | '/teacher/classes'
    | '/teachers/$teacherId'
    | '/classes/'
    | '/results/'
    | '/students/'
    | '/teacher/'
    | '/teachers/'
    | '/teacher/class/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AttendanceRoute: typeof AttendanceRoute
  CommunicationRoute: typeof CommunicationRoute
  ImportRoute: typeof ImportRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AcademicsLessonsRoute: typeof AcademicsLessonsRoute
  AcademicsSubjectsRoute: typeof AcademicsSubjectsRoute
  AcademicsSyllabusRoute: typeof AcademicsSyllabusRoute
  AcademicsTimetableRoute: typeof AcademicsTimetableRoute
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  ResultsBatchIdRoute: typeof ResultsBatchIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeachersTeacherIdRoute: typeof TeachersTeacherIdRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  TeacherClassClassIdRoute: typeof TeacherClassClassIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/lessons': {
      id: '/academics/lessons'
      path: '/academics/lessons'
      fullPath: '/academics/lessons'
      preLoaderRoute: typeof AcademicsLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/subjects': {
      id: '/academics/subjects'
      path: '/academics/subjects'
      fullPath: '/academics/subjects'
      preLoaderRoute: typeof AcademicsSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/syllabus': {
      id: '/academics/syllabus'
      path: '/academics/syllabus'
      fullPath: '/academics/syllabus'
      preLoaderRoute: typeof AcademicsSyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/timetable': {
      id: '/academics/timetable'
      path: '/academics/timetable'
      fullPath: '/academics/timetable'
      preLoaderRoute: typeof AcademicsTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$batchId': {
      id: '/results/$batchId'
      path: '/results/$batchId'
      fullPath: '/results/$batchId'
      preLoaderRoute: typeof ResultsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/teacher/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId': {
      id: '/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof TeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class/$classId': {
      id: '/teacher/class/$classId'
      path: '/teacher/class/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof TeacherClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  AttendanceRoute: AttendanceRoute,
  CommunicationRoute: CommunicationRoute,
  ImportRoute: ImportRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AcademicsLessonsRoute: AcademicsLessonsRoute,
  AcademicsSubjectsRoute: AcademicsSubjectsRoute,
  AcademicsSyllabusRoute: AcademicsSyllabusRoute,
  AcademicsTimetableRoute: AcademicsTimetableRoute,
  ClassesClassIdRoute: ClassesClassIdRoute,
  ResultsBatchIdRoute: ResultsBatchIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeachersTeacherIdRoute: TeachersTeacherIdRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  TeacherClassClassIdRoute: TeacherClassClassIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
