/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as TeachersIndexRouteImport } from './routes/teachers.index'
import { Route as TeachersTeacherIdRouteImport } from './routes/teachers.$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdRoute = TeachersTeacherIdRouteImport.update({
  id: '/teachers/$teacherId',
  path: '/teachers/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/students': typeof StudentsIndexRoute
  '/teachers': typeof TeachersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/students/': typeof StudentsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/students/$studentId'
    | '/teachers/$teacherId'
    | '/students/'
    | '/teachers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/students/$studentId'
    | '/teachers/$teacherId'
    | '/students'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/students/$studentId'
    | '/teachers/$teacherId'
    | '/students/'
    | '/teachers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  TeachersTeacherIdRoute: typeof TeachersTeacherIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId': {
      id: '/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof TeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  TeachersTeacherIdRoute: TeachersTeacherIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
